on: [push]

name: build

jobs:
  build:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install tools
        run: |
          npm install

      - name: typecheck with tsc
        run: |
          npm run typecheck

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install tools
        run: |
          npm install

      - name: check formatting
        run: |
          npm run lint
